# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumiveis',
            name='agilidade',
        ),
        migrations.RemoveField(
            model_name='consumiveis',
            name='poder_ataque',
        ),
        migrations.RemoveField(
            model_name='consumiveis',
            name='resistencia',
        ),
        migrations.RemoveField(
            model_name='consumiveis',
            name='vida',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='agilidade',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='poder_ataque',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='resistencia',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='vida',
        ),
        migrations.AddField(
            model_name='consumiveis',
            name='duracao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='durabilidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='tipo',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='itens',
            name='agilidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itens',
            name='poder_ataque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itens',
            name='resistencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itens',
            name='vida',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missoes',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanha_missao', to='webpage.Campanhas'),
        ),
    ]
