# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0002_auto_20161020_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSpaceHeroes',
            fields=[
                ('pk_log', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='missoes',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='herois',
            name='experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herois',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='missoes',
            name='nome',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='missoes',
            unique_together=set([('campanha', 'ordem')]),
        ),
    ]
